const imageCollectionActionTypes = {
  FETCH_IMAGES_SUCCESS:"FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_START:"FETCH_IMAGES_START",
  ADD_SINGLE_IMAGE_SUCCESS: "ADD_SINGLE_DATA_SUCCESS",
  ADD_SEARCH_KEYWORD_SUCCESS: "ADD_SEARCH_KEYWORD_SUCCESS",
  REMOVE_IMAGE_SUCCESS: "REMOVE_IMAGE_SUCCESS",
  TOGGLE_USER_TYPE:"TOGGLE_USER_TYPE",
  ADD_USER_ID:"ADD_USER_ID",
  ADD_USER:"ADD_USER"
};

export default imageCollectionActionTypes;
