const imageCollectionActionTypes = {
  FETCH_IMAGES_SUCCESS:"FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_START:"FETCH_IMAGES_START",
  ADD_SINGLE_IMAGE_SUCCESS: "ADD_SINGLE_DATA_SUCCESS",
  ADD_SEARCH_KEYWORD_SUCCESS: "ADD_SEARCH_KEYWORD_SUCCESS",
  REMOVE_IMAGE_SUCCESS: "REMOVE_IMAGE_SUCCESS"
};

export default imageCollectionActionTypes;
