const imageCollectionActionTypes = {
  FETCH_IMAGES_START:"FETCH_IMAGES_START",
  FETCH_IMAGES_SUCCESS:"FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_FAILURE:"FETCH_IMAGES_FAILURE",
  ADD_SINGLE_IMAGE: "ADD_SINGLE_DATA",
  ADD_SEARCH_KEYWORD: "ADD_SEARCH_KEYWORD",
  REMOVE_IMAGE: "REMOVE_IMAGE"
};

export default imageCollectionActionTypes;
